### PR TITLE
Write test for case with no script block

### PR DESCRIPTION
**Pull request by just-be-dev**
Adds a test for the case when no script block is present... it causes the codemod to fail

### CODE REVIEW

**Comment by just-be-dev** [comment]
I guess this test needs to be updated to live in the proper place... should also just add the code to fix the issue here. @psalaets If you could help with updating the test I can take a look at fixing the feature.

**Comment by psalaets** [comment]
Converting the test to the new setup will be some easy copy paste so no big deal on that.

Regarding the changes to get it passing, I think there are some potential tricky situations with this.

### Situation 1

Adapter would invoke `transform()` with `fileInfo.source` set to empty string. That's what jscodeshift does when it encounters an empty js file.

Tricky part: If `transform()` returns something, should a `<script>` be created in the sfc? If so where?

Maybe that use case isn't realistic so not worth worrying about. You could argue jscodeshift is more for transforming existing code, not creating code out of thin air?

### Situation 2

Similar to situation 1 but regarding the vue sfc support (`fileInfo.script`, `fileInfo.style`, `fileInfo.template`): I guess `transform()` would be invoked with `fileInfo.script` set to undefined since `fileInfo.script` represents the `<script>` itself and `fileInfo.script.content` represents the code inside it.

If `transform()` somehow sets `fileInfo.script.content`, I guess a `<script>` block would be created?


I do want to handle this use case, ideally anything that is a valid sfc should be supported by this module. Just need to figure out what makes sense and keeps things relatively straightforward.

**Comment by psalaets** [comment]
I'm thinking about doing #5 to simplify this a little. And "jscodeshift mode" seems like the much more common case.

Thinking a little more about Situation 1 above, maybe `transform()` shouldn't even be invoked for vue files with no `<script>`.

**Comment by psalaets** [comment]
The gist of this change ended up at https://github.com/psalaets/vue-jscodeshift-adapter/tree/master/tests/transforms/no-script-block

Thanks

**Pull request closed without merging**
